# Generated by Django 5.1.1 on 2024-09-24 07:27

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_tipoexame_tuss_tipoexame_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='agendado_para',
            field=slth.db.models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data',
            field=slth.db.models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='finalizado_em',
            field=slth.db.models.DateTimeField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='limite_webconf',
            field=slth.db.models.DateTimeField(null=True, verbose_name='Limite da WebConf'),
        ),
        migrations.AlterField(
            model_name='avaliacaoatendimento',
            name='data',
            field=slth.db.models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data',
            field=slth.db.models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='encaminhamentoscondutas',
            name='data',
            field=slth.db.models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horarioprofissionalsaude',
            name='data_hora',
            field=slth.db.models.DateTimeField(verbose_name='Data/Hora'),
        ),
    ]
