# Generated by Django 5.1.1 on 2024-10-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_especialidade_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CertificadoDigital",
        ),
    ]
