# Generated by Django 5.1.3 on 2024-11-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_certificadodigital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionalsaude',
            name='zoom_token',
        ),
    ]
