# Generated by Django 5.1.3 on 2024-11-22 03:34

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_profissionalsaude_zoom_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='limite_webconf',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='numero_webconf',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='senha_webconf',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='ciap',
            field=slth.db.models.ManyToManyField(blank=True, to='api.ciap', verbose_name='CIAP'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='cid',
            field=slth.db.models.ManyToManyField(blank=True, to='api.cid', verbose_name='CID'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='unidade',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unidade'),
        ),
    ]
