# Generated by Django 5.1.3 on 2024-11-22 03:59

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_atendimento_limite_webconf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='iniciado_em',
            field=slth.db.models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='agendado_para',
            field=slth.db.models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista'),
        ),
    ]
