# Generated by Django 5.1.3 on 2024-11-23 22:29

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_atendimento_iniciado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Situação de Atendimento',
                'verbose_name_plural': 'Situações de Atendimento',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='justificativa_horario_excepcional',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='situacao',
            field=slth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.situacaoatendimento', verbose_name='Situação'),
        ),
    ]
