# Generated by Django 5.1.3 on 2024-12-05 14:14

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_pessoafisica_sexo'),
        ('slth', '0012_timezone_remove_usertimezone_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='emails',
            field=slth.db.models.ManyToManyField(blank=True, to='slth.email', verbose_name='E-mails'),
        ),
        migrations.AddField(
            model_name='estado',
            name='fuso_horario',
            field=slth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slth.timezone', verbose_name='Fuso Horário'),
        ),
    ]
