# Generated by Django 5.1.3 on 2024-12-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_atendimento_emails_estado_fuso_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='unidade',
        ),
    ]
