# Generated by Django 5.1.3 on 2025-01-24 00:08

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_hora_confirmacao',
            field=slth.db.models.DateTimeField(null=True, verbose_name='Data/Hora da Confirmação'),
        ),
    ]
