# Generated by Django 5.1.1 on 2025-04-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_atendimento_data_hora_confirmacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissionalsaude",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
