# Generated by Django 5.1.1 on 2025-04-05 08:07

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_profissionalsaude_ativo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialApoio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "tipo",
                    slth.db.models.CharField(
                        choices=[("arquivo", "Arquivo"), ("url", "URL")],
                        max_length=255,
                        verbose_name="Tipo",
                    ),
                ),
                ("url", slth.db.models.CharField(max_length=255, verbose_name="URL")),
                (
                    "arquivo",
                    slth.db.models.FileField(
                        upload_to="materiais", verbose_name="Arquivo"
                    ),
                ),
                (
                    "objetivo",
                    slth.db.models.TextField(
                        blank=True, null=True, verbose_name="Objetivo"
                    ),
                ),
                (
                    "pessoa_fisica",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pessoafisica",
                        verbose_name="Cadastrador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia de Apoio",
                "verbose_name_plural": "Materiais de Apoio",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
