# Generated by Django 5.1.1 on 2025-04-05 08:11

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_materialapoio"),
    ]

    operations = [
        migrations.AddField(
            model_name="atendimento",
            name="materiais_apoio",
            field=slth.db.models.ManyToManyField(
                blank=True, to="api.materialapoio", verbose_name="Materiais de Apoio"
            ),
        ),
    ]
