# Generated by Django 5.1.1 on 2025-04-05 09:15

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_atendimento_materiais_apoio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialapoio",
            name="arquivo",
            field=slth.db.models.FileField(
                blank=True, null=True, upload_to="materiais", verbose_name="Arquivo"
            ),
        ),
        migrations.AlterField(
            model_name="materialapoio",
            name="url",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL"
            ),
        ),
    ]
