# Generated by Django 5.1.1 on 2025-04-20 10:03

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_materialapoio_arquivo_alter_materialapoio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissionalsaude",
            name="url_webconf",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL da Webconf"
            ),
        ),
    ]
