# Generated by Django 5.1.1 on 2025-05-04 10:18

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_profissionalsaude_url_webconf"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoafisica",
            name="data_hora_teste_dispositivo",
            field=slth.db.models.DateTimeField(
                blank=True, null=True, verbose_name="Data/Hora do Teste de Dispositivo"
            ),
        ),
        migrations.AddField(
            model_name="pessoafisica",
            name="evidencia_teste_dispositivo",
            field=slth.db.models.ImageField(
                blank=True,
                null=True,
                upload_to="teste_dispositvo",
                verbose_name="Evidência do Teste de Dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="data_hora_confirmacao",
            field=slth.db.models.DateTimeField(
                blank=True, null=True, verbose_name="Data/Hora da Confirmação"
            ),
        ),
    ]
