# Generated by Django 5.1.1 on 2025-05-05 08:28

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_pessoafisica_data_hora_teste_dispositivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', slth.db.models.CharField(max_length=80, verbose_name='Nome')),
                ('cpf', slth.db.models.CharField(max_length=14, unique=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Agendador',
                'verbose_name_plural': 'Agendadores',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
