# Generated by Django 5.1.1 on 2025-05-22 11:49

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_agendador"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialidade",
            name="duracao_minima_primeiro_atendimento",
            field=slth.db.models.IntegerField(
                choices=[(20, "20 minutos"), (40, "40 minutos"), (60, "60 minutos")],
                default=60,
                verbose_name="Duração Mínima do Primeiro Atendimento",
            ),
        ),
    ]
