application:
  lang: pt-br
  title: Telefiocruz
  subtitle: Telefiocruz - Telessaúde da Fiocruz
  icon: /static/images/icon.png
  logo: /static/images/logo.png
  version: 1.0.5
  sponsors:
    - /static/images/logos/logo4.png
  oauth: {}
  groups:
    a: Administrador
    g: Gestor de Núcleo
    o: Operador de Núcleo
    ps: Profissinal de Saúde
    p: Paciente
    gu: Gestor de Unidade
    ou: Operador de Unidade
  index: dashboard
  dashboard:
    toolbar:
    actions:
    top:
    center:
      - profissionalsaude.vinculos
      - profissionalsaude.proximosatendimentos
      - pessoafisica.proximosatendimentos
      - profissionalsaude.minhaagenda
    boxes:
      - abrirsala
      - pessoafisica.pessoasfisicas
      - nucleo.nucleos
      - unidade.unidades
      - profissionalsaude.profissionaissaude
      - profissionalsaude.definirhorarios
      - atendimento.atendimentos
      - atendimento.agenda
      - estatistica
    adder:
    search:
    usermenu:
      - profile.userprofile
      - user.users
      - log.logs
      - email.emails
      - pushsubscription.pushsubscriptions
      - job.jobs
      - deletion.deletions
      - auth.logout
    tools:
    settings:
  menu:
    user-gear:Administradores: administrador.administradores
    list:Cadastros Gerais:
      CIDs: cid.cids
      CIAPs: ciap.ciaps
      Conselhos de Classe: conselhoclasse.conselhosclasse
      Sexos: sexo.sexos
      Tipos de Atendimento: tipoatendimento.tiposatendimento
      Estados: estado.estados
      Municípios: municipio.municipios
      Áreas: area.areas
      Especialidades: especialidade.especialidades
      Tipos de Exame: tipoexame.tiposexame
      Medicamentos: medicamento.medicamentos
    building-user:Núcleos de Telessaúde: nucleo.nucleos
    building:Unidades de Saúde: unidade.unidades
    stethoscope:Profissionais de Saúde: profissionalsaude.profissionaissaude
    users:Pessoas Físicas: pessoafisica.pessoasfisicas
    laptop-file:Atendimentos: atendimento.atendimentos
  theme:
    colors:
      primary: "#265890"
      secondary: "#071e41"
      auxiliary: "#2670e8"
      highlight: "#0c326f"
      info: "#265890"
      success: "#5ca05d"
      warning: "#fff5c2"
      danger: "#e52207"
    border:
      radius: 100em"
    background:
      info: "#d4e5ff"
